extends: airbnb-base
rules:
  valid-jsdoc:
    - error
    -
      requireReturn: false
      preferType:
        Boolean: boolean
        Number: number
        Object: object
        String: string
